# Generated by CoffeeScript 1.10.0

extend = (child, parent) ->

  ctor = ->
    @constructor = child
    return

  for key of parent
    if hasProp.call(parent, key)
      child[key] = parent[key]
  ctor.prototype = parent.prototype
  child.prototype = new ctor
  child.__super__ = parent.prototype
  child

hasProp = {}.hasOwnProperty
define [
  'backbone'
  'backbone.marionette'
  'jknob'
], (Backbone, Marionette) ->
  FagerMainView = undefined
  FagerMainView = ((superClass) ->
    `var FagerMainView`

    FagerMainView = ->
      FagerMainView.__super__.constructor.apply this, arguments

    extend FagerMainView, superClass
    FagerMainView::model = new (Backbone.Model)
    FagerMainView::className = 'item calculadoras fager'
    FagerMainView::template = '#calc-fager-main-view'
    FagerMainView::ui =
      'resposta': '.condutaBox'
      'resultado': 'input.grafResult'
      'escoreBox': '.escoreBox'
      'condutaBox': '.condutaBox'
      'descricao': '.descricao'
      'mortalidade': '.mortalidade'
      'qst10': '#Q10'
      'qst11': '#Q11'
      'qst12': '#Q12'
      'qst13': '#Q13'
      'qst20': '#Q20'
      'qst21': '#Q21'
      'qst22': '#Q22'
      'qst23': '#Q23'
      'qst30': '#Q30'
      'qst31': '#Q31'
      'qst40': '#Q40'
      'qst41': '#Q41'
      'qst50': '#Q50'
      'qst51': '#Q51'
      'qst60': '#Q60'
      'qst61': '#Q61'
    FagerMainView::events =
      'change @ui.qst10': 'changeDados'
      'change @ui.qst11': 'changeDados'
      'change @ui.qst12': 'changeDados'
      'change @ui.qst13': 'changeDados'
      'change @ui.qst20': 'changeDados'
      'change @ui.qst21': 'changeDados'
      'change @ui.qst22': 'changeDados'
      'change @ui.qst23': 'changeDados'
      'change @ui.qst30': 'changeDados'
      'change @ui.qst31': 'changeDados'
      'change @ui.qst40': 'changeDados'
      'change @ui.qst41': 'changeDados'
      'change @ui.qst50': 'changeDados'
      'change @ui.qst51': 'changeDados'
      'change @ui.qst60': 'changeDados'
      'change @ui.qst61': 'changeDados'

    FagerMainView::changeDados = ->
      q1 = undefined
      dados = undefined
      total = undefined
      resultado = undefined
      tab = undefined
      dados = @getDados()
      total = parseFloat(dados.q1) + parseFloat(dados.q2) + parseFloat(dados.q3) + parseFloat(dados.q4) + parseFloat(dados.q5) + parseFloat(dados.q6)
      tab = @tabela.crb
      resultado = _(tab).find((item) ->
        item.pontos.indexOf(total) != -1
      )
      console.log resultado.descricao
      @ui.resultado.val(total).trigger 'change'
      @ui.descricao.text resultado.descricao
      @ui.escoreBox.fadeIn()
      return @ui.resposta.show()
      if total
      else
      return

    FagerMainView::getDados = ->
      r = undefined
      q1 = undefined
      q2 = undefined
      q3 = undefined
      q4 = undefined
      q5 = undefined
      q6 = undefined
      q1 = q2 = q3 = q4 = q5 = q6 = 0
      if @ui.qst10.prop('checked')
        q1 = 0
      if @ui.qst11.prop('checked')
        q1 = 1
      if @ui.qst12.prop('checked')
        q1 = 2
      if @ui.qst13.prop('checked')
        q1 = 3
      if @ui.qst20.prop('checked')
        q2 = 0
      if @ui.qst21.prop('checked')
        q2 = 1
      if @ui.qst22.prop('checked')
        q2 = 2
      if @ui.qst23.prop('checked')
        q2 = 3
      if @ui.qst30.prop('checked')
        q3 = 0
      if @ui.qst31.prop('checked')
        q3 = 1
      if @ui.qst40.prop('checked')
        q4 = 0
      if @ui.qst41.prop('checked')
        q4 = 1
      if @ui.qst50.prop('checked')
        q5 = 0
      if @ui.qst51.prop('checked')
        q5 = 1
      if @ui.qst60.prop('checked')
        q6 = 0
      if @ui.qst61.prop('checked')
        q6 = 1
      r =
        q1: q1
        q2: q2
        q3: q3
        q4: q4
        q5: q5
        q6: q6
      r

    FagerMainView::tabela = crb: [
      {
        pontos: [
          0
          1
          2
        ]
        descricao: 'muito baixa dependência física'
      }
      {
        pontos: [
          3
          4
        ]
        descricao: 'baixa dependência física'
      }
      {
        pontos: [ 5 ]
        descricao: 'média dependência física'
      }
      {
        pontos: [
          6
          7
        ]
        descricao: 'elevada dependência física'
      }
      {
        pontos: [
          8
          9
          10
        ]
        descricao: 'muito elevada dependência física'
      }
    ]

    FagerMainView::setKnob = (max) ->
      max = 10
      @ui.resultado.knob
        width: '190'
        lineCap: 'round'
        inline: true
        bgColor: '#f1f1f1'
        inputColor: '#444'
        max: max
        thickness: '.2'
        readOnly: true
        format: (value) ->
          value

    FagerMainView::onRender = (view) ->
      @setKnob()
      @ui.escoreBox.hide()
      @ui.condutaBox.hide()

    FagerMainView
  )(Marionette.ItemView)
  FagerMainView

# ---
# generated by js2coffee 2.2.0