print("mongo init start --------------------");

db.getSiblingDB("admin").auth("mamongo", "mamongo");
db.createUser({
  user: "mamongo",
  pwd: "mamongo",
  roles: [
    {
      role: "readWrite",
      db: "mamongo",
    },
  ],
});

db = db.getSiblingDB("modulos");
db.createCollection("modulos", { capped: false });
db.modulos.insert({
  _id: ObjectId("63758ed55ebc0215731f6c36"),
  components: [
    {
      folder: "intro",
      short: "Introduz",
      title: "Abertura do App",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "badge",
      short: "Badge",
      title: "Modais de Badge",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "local-storage",
      short: "Local Storage",
      title: "Local Data Storage",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "store-manager",
      short: "Manager",
      title: "Store Manager",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "progresso",
      short: "Progresso",
      title: "Monitor Progresso",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "lti",
      short: "LTI",
      title: "Recurso LTI",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "websocket",
      short: "Socket",
      title: "WebSocket Connection Component",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "teste-progresso",
      short: "Teste Progresso",
      title: "Um Teste com Progresso",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "idle-warn",
      short: "Inatividade",
      title: "Controle de Inatividade",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "saiba-mais",
      short: "Siaba Mais",
      title: "Siaba Mais",
      categories: ["ferramenta"],
      hidemenu: true,
    },
    {
      folder: "caso-progresso",
      short: "Caso Interativo",
      title: "Um Caso",
      categories: ["ferramenta"],
      hidemenu: true,
    },
    {
      folder: "materiais",
      short: "Materiais de Apoio",
      title: "Materiais de Apoio ao Aprendizado",
      categories: ["material-apoio"],
      externalResources: true,
      ref: "materiais",
      match: { modulo: ObjectId("63758ed55ebc0215731f6c36") },
    },
    {
      folder: "bibliografia",
      short: "Bibliografia",
      title: "Bibliografia Geral",
      categories: ["material-apoio"],
      externalResources: true,
      ref: "bibliografias",
      match: { modulo: ObjectId("63758ed55ebc0215731f6c36") },
    },
    {
      folder: "home",
      short: "Inicie por aqui",
      title: "Página inicial",
      categories: ["indice"],
    },
    {
      folder: "cadastro",
      short: "cadastro",
      title: "cadastro",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "selecao-progresso",
      short: "Casos Interativos",
      title: "Casos Interativos",
      categories: ["indice"],
      sources: [],
      externalResources: true,
      ref: "selecoes",
      oid: "638ce58070428362382f7506",
    },
    {
      folder: "listatestes",
      short: "Testes",
      title: "Testes",
      categories: ["indice"],
      sources: [],
      externalResources: true,
      ref: "selecoes",
      oid: "638ce4c870428362382f7501",
    },
    {
      folder: "video-player",
      short: "video player",
      title: "",
      categories: ["infraestrutura"],
      sources: [
        {
          filename: "apresentacao_surtos_epidemias",
          resolution: "1080p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (min-width: 991px)",
        },
      ],
      poster: "investigacao_surtos_capa_apresentacao.png",
    },
    {
      folder: "video-player",
      short: "video player",
      title: "Por que investigar surtos e pandemias ?",
      categories: ["infraestrutura"],
      sources: [
        {
          filename: "investigacao_surtos_aula_1",
          resolution: "1080p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (min-width: 991px)",
        },
        {
          filename: "investigacao_surtos_aula_1",
          resolution: "720p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (max-width: 990px)",
        },
      ],
      poster: "investigacao_surtos_aula_1_capa.png",
    },
    {
      folder: "video-player",
      short: "video player",
      title: "Como realizar a investigação de surtos e pandemias",
      categories: ["infraestrutura"],
      sources: [
        {
          filename: "investigacao_surtos_aula_2",
          resolution: "1080p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (min-width: 991px)",
        },
        {
          filename: "investigacao_surtos_aula_2",
          resolution: "720p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (max-width: 990px)",
        },
      ],
      poster: "investigacao_surtos_aula_2_capa.png",
    },
    {
      folder: "video-player",
      short: "video player",
      title: "10 passos para a investigação de surtos e pandemias",
      categories: ["infraestrutura"],
      sources: [
        {
          filename: "investigacao_surtos_aula_3",
          resolution: "1080p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (min-width: 991px)",
        },
        {
          filename: "investigacao_surtos_aula_3",
          resolution: "720p",
          extension: "mp4",
          mime: "video/mp4",
          mediaQuery: "all and (max-width: 990px)",
        },
      ],
      poster: "investigacao_surtos_aula_3_capa.png",
    },
    {
      folder: "logout",
      short: "Sair",
      title: "Sair do App",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "enquetes",
      short: "Enquete",
      title: "Enquetes",
      categories: ["infraestrutura"],
      hidemenu: true,
    },
    {
      folder: "investigacao-surtos-ficha-tecnica",
      short: "Créditos",
      title: "Ficha técnica",
      categories: ["conteudo"],
    },
    {
      folder: "dashboard",
      short: "dashboard",
      title: "Dashboard",
      categories: ["conteudo"],
    },
  ],
  name: "Investigação de surtos e epidemias",
  navigateOnStart: "comp/home",
  shortname: "investigacao_surtos",
  corPadraoMenu: "eaf9f8",
  corPadraoMenuDestaque: "cbe8e5",
  url_publica: "/investigacao_surtos",
  corPadrao: "1961AC",
  customMenu: [
    { path: "#comp/home", name: "Inicial" },
    { path: "#comp/listatestes", name: "Testes" },
    { path: "#comp/selecao-progresso", name: "Casos Interativos" },
    { path: "#comp/materiais", name: "Material de Apoio" },
    { path: "#comp/bibliografia", name: "Bibliografia" },
    { path: "#comp/investigacao-surtos-ficha-tecnica", name: "Ficha Técnica" },
    { path: "#comp/enquetes", name: "Enquetes" },
  ],
  fl_unidades: true,
  img_video_apresentacao: "investigacao_surtos_capa_apresentacao.png",
  showComponentMenu: false,
  skipIntro: false,
  style: {
    "dropdown-menu>li>a": ["color: inherit!important"],
    "mdi-home": ["color: inherit!important", "margin-bottom: 5px"],
  },
  fl_layout_alternativo: true,
  videos_extra: [
    {
      col: "col-md-4 col-12",
      videos: [
        {
          title: "",
          subtitle: "",
          tip: "",
          img: "investigacao_surtos_aula_1_capa.png",
          source: "investigacao_surtos_aula_1",
        },
        {
          title: "",
          subtitle: "",
          tip: "",
          img: "investigacao_surtos_aula_2_capa.png",
          source: "investigacao_surtos_aula_2",
        },
        {
          title: "",
          subtitle: "",
          tip: "",
          img: "investigacao_surtos_aula_3_capa.png",
          source: "investigacao_surtos_aula_3",
        },
      ],
    },
  ],
  subtitle: "Curso de Autoaprendizagem",
  corPadraoCurso: "3C9687",
  intro_img_2: "marcas/Logos coloridos - curso ITPS-01-ITPS.svg",
  intro_img_2_alt: "Instituto Todos Pela Saúde",
  intro_img_3: "marcas/Logos coloridos - curso ITPS-02-Abrasco.svg",
  intro_img_3_alt: "Abrasco",
});
print("mongo init end --------------------");
/*

*/
