# Generated by CoffeeScript 1.10.0

extend = (child, parent) ->

  ctor = ->
    @constructor = child
    return

  for key of parent
    if hasProp.call(parent, key)
      child[key] = parent[key]
  ctor.prototype = parent.prototype
  child.prototype = new ctor
  child.__super__ = parent.prototype
  child

hasProp = {}.hasOwnProperty
define [
  'backbone'
  'backbone.marionette'
  'jknob'
], (Backbone, Marionette) ->
  CtabMainView = undefined
  CtabMainView = ((superClass) ->
    `var CtabMainView`

    CtabMainView = ->
      CtabMainView.__super__.constructor.apply this, arguments

    extend CtabMainView, superClass
    CtabMainView::model = new (Backbone.Model)
    CtabMainView::className = 'item calculadoras ctab'
    CtabMainView::template = '#calc-ctab-main-view'
    CtabMainView::ui =
      'resposta': '.condutaBox'
      'escoreBox': '.escoreBox'
      'condutaBox': '.condutaBox'
      'cigadia': '#cigadia'
      'anostab': '#anostab'
      'resultado': '.resultado'
    CtabMainView::events =
      'keyup @ui.anostab': 'changeDados'
      'keyup @ui.cigadia': 'changeDados'

    CtabMainView::changeDados = ->
      cigadia = undefined
      anostab = undefined
      resultado = undefined
      dados = @getDados()
      console.log 'x'
      resultado = parseInt(dados.cigadia / 20 * dados.anostab)
      if resultado > 0
        @ui.resultado.text resultado + ' anos-maços'
      @ui.escoreBox.fadeIn()
      @ui.resposta.show()

    CtabMainView::getDados = ->
      r = undefined
      cigadia = undefined
      anostab = undefined
      cigadia = 0
      anostab = 0
      if @ui.anostab.prop('value') > 0
        anostab = @ui.anostab.prop('value')
      if @ui.cigadia.prop('value') > 0
        cigadia = @ui.cigadia.prop('value')
      r =
        cigadia: cigadia
        anostab: anostab
      r

    CtabMainView::onRender = (view) ->
      @ui.escoreBox.hide()
      @ui.condutaBox.hide()

    CtabMainView
  )(Marionette.ItemView)
  CtabMainView

# ---
# generated by js2coffee 2.2.0