OfertasUsuarios = require('../app/models/ofertasUsuarios.coffee')
# var Progresso = require('../models/progresso.js');
# var Pedido = require('../models/pedido.js');
# var _ = require('underscore');
async = require('async')
#e os que mudam de oferta???
OfertasUsuarios.find({$and:[ { dt_conclusao: { $exists: true}}, { dt_cadastro: { $exists: true}}, { nr_horas: { $exists: false}}]}).limit(50000).exec (err, vinculos) ->
  if err
    throw err
  # v= vinculos[0];
  # horas = (v.dt_conclusao.getTime() - v.dt_cadastro.getTime())/(1000*60*60);
  console.log('alunos a calcular: ', vinculos.length);

  iter = (v, next) ->
    horas = 0
    if v.dt_conclusao
      horas = (v.dt_conclusao.getTime() - v.dt_cadastro.getTime()) / (1000 * 60 * 60)
    OfertasUsuarios.update { _id: v._id }, { $set: {nr_horas: horas} }, (err, num) ->
      if err
        next err
      else
        next()

  ffinal = (err) ->
    console.log err, 'final'
    if err
      process.exit -1
    else
      process.exit 1

  async.each vinculos, iter, ffinal
  return

# ---
# generated by js2coffee 2.2.0